# -*- coding: utf-8 -*-
"""Missingness Heatmap exp 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dhJEX1aFBTbLPcJ6w4ro0scbKTwXiNMm
"""

# ==============================
# IMPORT LIBRARIES
# ==============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages
from google.colab import files

# ==============================
# LOAD DATASET
# ==============================
df = pd.read_csv("/content/placement_predict_50k.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nFirst 5 rows:")
display(df.head())

# ==============================
# SET STYLE
# ==============================
sns.set_style("whitegrid")

# ==============================
# 1. MISSINGNESS HEATMAP
# ==============================
fig1 = plt.figure(figsize=(10, 6))

sns.heatmap(
    df.isnull(),
    cbar=False,
    cmap="viridis",
    yticklabels=False
)

plt.title("Missingness Heatmap - Placement Prediction Dataset")
plt.xlabel("Columns")
plt.tight_layout()
plt.show()


# ==============================
# NUMERICAL COLUMNS
# ==============================
num_cols = df.select_dtypes(include=np.number).columns

print("\nNumerical Columns:")
print(list(num_cols))


# ==============================
# 2. DISTRIBUTION PLOTS
# ==============================
fig2, axes = plt.subplots(2, 3, figsize=(15, 8))

for i, column in enumerate(num_cols[:6]):

    row, colpos = divmod(i, 3)

    sns.histplot(
        df[column].dropna(),
        bins=30,
        kde=True,
        ax=axes[row, colpos]
    )

    axes[row, colpos].set_title(f"Distribution of {column}")
    axes[row, colpos].set_xlabel(column)
    axes[row, colpos].set_ylabel("Frequency")

plt.tight_layout()
plt.show()


# ==============================
# 3. CORRELATION HEATMAP
# ==============================
fig3 = plt.figure(figsize=(10, 8))

corr_matrix = df[num_cols].corr()

sns.heatmap(
    corr_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    square=True,
    linewidths=0.5
)

plt.title("Correlation Heatmap - Numerical Features")
plt.tight_layout()
plt.show()


# ==============================
# 4. BOX PLOTS
# ==============================
fig4, axes4 = plt.subplots(2, 3, figsize=(15, 8))

for i, column in enumerate(num_cols[:6]):

    row, colpos = divmod(i, 3)

    sns.boxplot(
        y=df[column],
        ax=axes4[row, colpos]
    )

    axes4[row, colpos].set_title(f"Boxplot of {column}")
    axes4[row, colpos].set_ylabel(column)

plt.tight_layout()
plt.show()


# ==============================
# 5. CREATE PDF REPORT
# ==============================
pdf = PdfPages("/content/EDA_Report.pdf")

pdf.savefig(fig1, bbox_inches="tight")
pdf.savefig(fig2, bbox_inches="tight")
pdf.savefig(fig3, bbox_inches="tight")
pdf.savefig(fig4, bbox_inches="tight")

pdf.close()

print("\nEDA_Report.pdf has been created successfully!")


# ==============================
# 6. DOWNLOAD PDF
# ==============================
files.download("/content/EDA_Report.pdf")